# Generated by Django 5.1.7 on 2025-03-28 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='expender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='occasion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.occasion'),
        ),
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.event'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utlizers',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.event'),
        ),
        migrations.AddField(
            model_name='utlizers',
            name='utlizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilized_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
